services:
  app:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped

    environment:
      HTTP_PORT: ${HTTP_PORT}
      HTTPS_PORT: ${HTTPS_PORT}
      DB_MYSQL_HOST: ${DB_MYSQL_HOST}
      DB_MYSQL_PORT: ${DB_MYSQL_PORT}
      DB_MYSQL_USER: ${DB_MYSQL_USER}
      DB_MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      DB_MYSQL_NAME: ${DB_MYSQL_NAME}
      TZ: ${TZ}

    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
      - "${HTTPS_PORT}:${HTTPS_PORT}"
      - "${ADMIN_PORT}:${ADMIN_PORT}"

    volumes:
      # 由 ctl 渲染后的最终文件（固定文件名与 NPM 预期一致）
      - ./.rendered/_listen.conf:/app/templates/_listen.conf:rw
      - ./.rendered/default.conf:/etc/nginx/conf.d/default.conf:rw
      # 数据卷
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

    depends_on:
      - db

  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${DB_MYSQL_NAME}
      MYSQL_USER: ${DB_MYSQL_USER}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      TZ: ${TZ}
      MARIADB_AUTO_UPGRADE: '1'
    volumes:
      - ./mysql:/var/lib/mysql